# Generated by Django 5.1.5 on 2026-04-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('vibX', models.FloatField()),
                ('vibY', models.FloatField()),
                ('vibZ', models.FloatField()),
                ('rms', models.FloatField()),
                ('crest', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
