# Generated by Django 5.1.5 on 2026-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='cv',
            field=models.FloatField(default=0.0),
        ),
    ]
