# Generated by Django 5.1.5 on 2026-04-20 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0003_motor_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='motor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensores.motor'),
        ),
    ]
