# Generated by Django 5.1.5 on 2026-04-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0004_leitura_motor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorCalibration',
            fields=[
                ('motor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sensores.motor')),
                ('offset_x', models.FloatField(default=0.0)),
                ('offset_y', models.FloatField(default=0.0)),
                ('offset_z', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
