# Generated by Django 5.1.5 on 2026-04-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0005_motorcalibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='ultimo_alerta_enviado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
