# Generated by Django 5.1.5 on 2026-04-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0006_motor_ultimo_alerta_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='limite_alerta',
            field=models.FloatField(default=4.5),
        ),
    ]
