# Generated by Django 5.1.5 on 2026-04-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0007_motor_limite_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='limite_kurtosis',
            field=models.FloatField(default=3.5),
        ),
    ]
